### ISSUE TITLE
Prometheus metric `velero_backup_active_total` does not exist 

### ISSUE THREAD

**Issue by alessandrolomanto** [sighupio/fury-kubernetes-dr#50]
The panel of the reference dasboard has no more values:

https://github.com/sighupio/fury-kubernetes-dr/blob/522198f560077c5df81d8460314dd1ab4f53debb/katalog/velero/velero-base/dashboards/velero.json#L120
https://github.com/sighupio/fury-kubernetes-dr/blob/522198f560077c5df81d8460314dd1ab4f53debb/katalog/velero/velero-base/dashboards/velero.json#L396

This  problem has been tested with the following `Furyfile.yaml` specifications:
```
versions:
  networking: v1.8.2
  monitoring: v1.14.1
  logging: v1.10.2
  ingress: v1.12.2
  dr: v1.9.2

bases:
  - name: monitoring/prometheus-operator
  - name: monitoring/prometheus-operated
  - name: monitoring/grafana
  - name: monitoring/goldpinger
  - name: monitoring/configs
  - name: monitoring/kubeadm-sm
  - name: monitoring/kube-proxy-metrics
  - name: monitoring/kube-state-metrics
  - name: monitoring/node-exporter
  - name: monitoring/metrics-server
  - name: monitoring/eks-sm
  - name: monitoring/alertmanager-operated
  - name: logging/elasticsearch-single
  - name: logging/cerebro
  - name: logging/curator
  - name: logging/fluentd
  - name: logging/kibana
  - name: ingress/nginx
  - name: ingress/forecastle
  - name: ingress/cert-manager
  - name: dr/velero/velero-aws
  
modules:
- name: dr/eks-velero

```
